spring:
  application:
    name: notification-service

  kafka:
    bootstrap-servers: localhost:29092

  mail:
    username: ${MAIL_USERNAME:default@example.com}
    password: ${MAIL_PASSWORD:default}
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true