version: '3.9'

services:
  # Database for Account Management Service
  ams-db:
    image: postgres:15
    container_name: ams-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: amspass
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ams-data:/var/lib/postgresql/data

  # Database for Investment Advisory Service
  ias-db:
    image: postgres:15
    container_name: ias-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: iaspass
      POSTGRES_DB: postgres
    ports:
      - "2345:5432"
    volumes:
      - ias-data:/var/lib/postgresql/data

  # Connecting Zookeeper for Kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  # Connecting Kafka itself
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  # Connecting Kafka UI
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka
    ports:
      - 8090:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181

volumes:
  ams-data:
  ias-data: