version: '3.9'

services:
  # Database for Account Management Service
  ams-db:
    image: postgres:15
    container_name: ams-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: amspass
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ams-data:/var/lib/postgresql/data

  # Database for Investment Advisory Service
  ias-db:
    image: postgres:15
    container_name: ias-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: iaspass
      POSTGRES_DB: postgres
    ports:
      - "2345:5432"
    volumes:
      - ias-data:/var/lib/postgresql/data

volumes:
  ams-data:
  ias-data: